version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./tmp/docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - ./tmp/docker/transmission/downloads:/downloads
      - ./tmp/docker/transmission/config:/config
      - ./tmp/docker/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
